export const wasteTypes = [
  {
    id: 1,
    name: "Botol PET Bening",
    category: "Plastik",
    is_eligible: true,
    reference_price_per_kg: 4500,
    reference_unit: "Kg",
    description: "Botol minuman bening dari bahan PET. Dijual mahal jika bersih, kering, dan label dilepas.",
  },
  {
    id: 2,
    name: "Botol Plastik Berwarna",
    category: "Plastik",
    is_eligible: true,
    reference_price_per_kg: 2500,
    reference_unit: "Kg",
    description: "Botol plastik bekas minuman atau pembersih dengan warna.",
  },
  {
    id: 3,
    name: "Plastik Kresek (HDPE/LDPE)",
    category: "Plastik",
    is_eligible: true,
    reference_price_per_kg: 800,
    reference_unit: "Kg",
    description: "Kantong plastik belanjaan, bersih dan kering.",
  },
  {
    id: 4,
    name: "Gelas Plastik",
    category: "Plastik",
    is_eligible: true,
    reference_price_per_kg: 3000,
    reference_unit: "Kg",
    description: "Gelas plastik bekas minuman, label dilepas.",
  },
  {
    id: 5,
    name: "Kardus",
    category: "Kertas",
    is_eligible: true,
    reference_price_per_kg: 2200,
    reference_unit: "Kg",
    description: "Kardus bekas paket atau dus elektronik. Harus kering.",
  },
  {
    id: 6,
    name: "Koran Bekas",
    category: "Kertas",
    is_eligible: true,
    reference_price_per_kg: 2800,
    reference_unit: "Kg",
    description: "Koran bekas dalam kondisi kering dan tidak basah.",
  },
  {
    id: 7,
    name: "Buku/HVS",
    category: "Kertas",
    is_eligible: true,
    reference_price_per_kg: 2000,
    reference_unit: "Kg",
    description: "Buku, majalah, atau kertas HVS bekas.",
  },
  {
    id: 8,
    name: "Duplex",
    category: "Kertas",
    is_eligible: true,
    reference_price_per_kg: 1200,
    reference_unit: "Kg",
    description: "Karton dua lapis bekas kemasan makanan.",
  },
  {
    id: 9,
    name: "Kaleng Aluminium",
    category: "Logam",
    is_eligible: true,
    reference_price_per_kg: 14000,
    reference_unit: "Kg",
    description: "Kaleng minuman ringan, bir, dan kemasan aluminium lain.",
  },
  {
    id: 10,
    name: "Besi Bekas",
    category: "Logam",
    is_eligible: true,
    reference_price_per_kg: 4500,
    reference_unit: "Kg",
    description: "Potongan besi rumahan, paku, jeruji, atau barang logam bekas.",
  },
  {
    id: 11,
    name: "Tembaga",
    category: "Logam",
    is_eligible: true,
    reference_price_per_kg: 75000,
    reference_unit: "Kg",
    description: "Kabel tembaga atau pipa tembaga bekas.",
  },
  {
    id: 12,
    name: "Botol Kaca Bening",
    category: "Botol Kaca",
    is_eligible: true,
    reference_price_per_kg: 500,
    reference_unit: "Kg",
    description: "Botol kecap, sirup, atau saus dari kaca bening.",
  },
  {
    id: 13,
    name: "Botol Kaca Warna",
    category: "Botol Kaca",
    is_eligible: true,
    reference_price_per_kg: 300,
    reference_unit: "Kg",
    description: "Botol kaca berwarna hijau atau cokelat.",
  },
  {
    id: 14,
    name: "Limbah Elektronik (E-waste)",
    category: "Elektronik",
    is_eligible: true,
    reference_price_per_kg: 6000,
    reference_unit: "Kg",
    description: "Komputer, ponsel, charger, baterai, dan elektronik kecil bekas.",
  },
  {
    id: 15,
    name: "Sampah Organik",
    category: "Organik",
    is_eligible: false,
    reference_price_per_kg: 0,
    reference_unit: "Kg",
    description: "Sisa makanan, daun, dan kulit buah. Biasanya lebih cocok untuk kompos.",
  },
  {
    id: 16,
    name: "Styrofoam",
    category: "Plastik",
    is_eligible: false,
    reference_price_per_kg: 0,
    reference_unit: "Kg",
    description: "Tidak banyak diterima bank sampah, sebaiknya dikurangi pemakaiannya.",
  },
];

export const wasteCategories = [
  "Semua",
  "Botol Kaca",
  "Elektronik",
  "Kertas",
  "Logam",
  "Organik",
  "Plastik",
];
